/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package kladara;

import java.awt.Color;
import java.awt.Component;
import java.awt.Point;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JTable;
import javax.swing.UIManager;
import pojo.Tipster;
import pomocni.Pomocna;
import pomocni.PomocnaBaza;
import pomocni.Poruka;

/**
 *
 * @author damirl
 */
public class DetaljPrometPregled extends javax.swing.JDialog {

    /**
     * Creates new form TipseriPregled
     */
    String selectSQL = "";

    public DetaljPrometPregled(Component parent, boolean modal, String datumOd, String datumDo, Object tipster, int igram) {
        super();
        initComponents();
        setLocationRelativeTo(parent);
        Pomocna.igramUComboBox(jComboBoxIgram);
        //Parametri
        jFormattedTextFieldDatumOd.setText(datumOd);
        jFormattedTextFieldDatumDo.setText(datumDo);
        jFormattedTextFieldTipster.setValue(tipster);
        jComboBoxIgram.setSelectedIndex(igram);
        napraviSelectSQL();
        try {
            tablica.refresh();
            totalSQL();
            postavkeTablica();
        } catch (SQLException ex) {
            Poruka.greska(this, ex.getMessage());
        }
        this.getRootPane().setDefaultButton(jButtonIzlaz);
        Pomocna.postavkeProzora(this,null);
        setVisible(true);
        lokacijaPoljaTotala();
        setModal(modal);
        tablica.selectCell(0, 0, true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablica = new quick.dbtable.DBTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextFieldDatumOd = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFieldDatumDo = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextFieldTipster = new javax.swing.JFormattedTextField();
        jTextFieldTipsterNaziv = new javax.swing.JTextField();
        jComboBoxIgram = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextFieldSUlog = new javax.swing.JFormattedTextField();
        jFormattedTextFieldSDobitak = new javax.swing.JFormattedTextField();
        jFormattedTextFieldSSaldo = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextFieldSROI = new javax.swing.JFormattedTextField();
        jButtonIzlaz = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Promet");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(1100, 700));
        setPreferredSize(new java.awt.Dimension(1100, 700));
        setResizable(false);

        tablica.setConnection(Konekcija.konekcija);
        tablica.setMaximumSize(new java.awt.Dimension(1100, 541));
        tablica.setMinimumSize(new java.awt.Dimension(1100, 541));
        tablica.setPreferredSize(new java.awt.Dimension(1100, 541));
        tablica.setSelectSql("SELECT\n    A.Id,\n    A.Datum,\n    A.TIPSTER_ID Tipster,\n    C.Naziv,\n    A.Opis Opis,\n    A.Ulog,\n    A.Koeficijent,\n    A.Dobitak,\n    A.Saldo,\n    A.STATUS_ID Status,\n    B.Naziv,\n    A.Igram,\n    A.Napomena\nFROM\n    PROMET A\n    JOIN STATUS B ON B.ID=A.STATUS_ID\n    JOIN TIPSTER C ON C.ID=A.TIPSTER_ID ");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel2.setMaximumSize(new java.awt.Dimension(1100, 80));
        jPanel2.setMinimumSize(new java.awt.Dimension(1100, 80));
        jPanel2.setPreferredSize(new java.awt.Dimension(1100, 80));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Datum od");

        jFormattedTextFieldDatumOd.setEditable(false);
        jFormattedTextFieldDatumOd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jFormattedTextFieldDatumOd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("do");

        jFormattedTextFieldDatumDo.setEditable(false);
        jFormattedTextFieldDatumDo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jFormattedTextFieldDatumDo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Tipster");

        jFormattedTextFieldTipster.setEditable(false);
        jFormattedTextFieldTipster.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("######"))));
        jFormattedTextFieldTipster.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jFormattedTextFieldTipster.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jFormattedTextFieldTipsterPropertyChange(evt);
            }
        });

        jTextFieldTipsterNaziv.setEditable(false);
        jTextFieldTipsterNaziv.setBackground(java.awt.SystemColor.controlHighlight);
        jTextFieldTipsterNaziv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldTipsterNaziv.setForeground(new java.awt.Color(0, 0, 153));
        jTextFieldTipsterNaziv.setFocusable(false);

        jComboBoxIgram.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxIgram.setEnabled(false);
        jComboBoxIgram.setFocusable(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Igram");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jFormattedTextFieldDatumOd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jFormattedTextFieldDatumDo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jFormattedTextFieldTipster, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldTipsterNaziv, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxIgram, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(303, 303, 303))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jFormattedTextFieldDatumOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jFormattedTextFieldDatumDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jFormattedTextFieldTipster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTipsterNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxIgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jFormattedTextFieldSUlog.setEditable(false);
        jFormattedTextFieldSUlog.setBackground(java.awt.SystemColor.controlHighlight);
        jFormattedTextFieldSUlog.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###,##0.00"))));
        jFormattedTextFieldSUlog.setFocusable(false);
        jFormattedTextFieldSUlog.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jFormattedTextFieldSDobitak.setEditable(false);
        jFormattedTextFieldSDobitak.setBackground(java.awt.SystemColor.controlHighlight);
        jFormattedTextFieldSDobitak.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###,##0.00"))));
        jFormattedTextFieldSDobitak.setFocusable(false);
        jFormattedTextFieldSDobitak.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jFormattedTextFieldSSaldo.setEditable(false);
        jFormattedTextFieldSSaldo.setBackground(java.awt.SystemColor.controlHighlight);
        jFormattedTextFieldSSaldo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###,##0.00"))));
        jFormattedTextFieldSSaldo.setFocusable(false);
        jFormattedTextFieldSSaldo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Total");

        jFormattedTextFieldSROI.setEditable(false);
        jFormattedTextFieldSROI.setBackground(java.awt.SystemColor.controlHighlight);
        jFormattedTextFieldSROI.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00%"))));
        jFormattedTextFieldSROI.setFocusable(false);
        jFormattedTextFieldSROI.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jButtonIzlaz.setMnemonic('z');
        jButtonIzlaz.setText("Izlaz");
        jButtonIzlaz.setMaximumSize(new java.awt.Dimension(80, 30));
        jButtonIzlaz.setMinimumSize(new java.awt.Dimension(80, 30));
        jButtonIzlaz.setPreferredSize(new java.awt.Dimension(80, 30));
        jButtonIzlaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzlazActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablica, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(111, 111, 111)
                .addComponent(jFormattedTextFieldSUlog, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jFormattedTextFieldSDobitak, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldSSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldSROI, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonIzlaz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(tablica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonIzlaz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jFormattedTextFieldSUlog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFormattedTextFieldSDobitak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFormattedTextFieldSSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jFormattedTextFieldSROI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void postavkeTablica() {
        tablica.getTable().setAutoResizeMode(JTable.AUTO_RESIZE_SUBSEQUENT_COLUMNS);
        tablica.setEditable(false);

        //Kolone
        //Id
        tablica.getColumn(0).setMaxWidth(60);
        tablica.getColumn(0).setHeaderValue("Id");
        //Datum
        tablica.getColumn(1).setMinWidth(90);
        tablica.getColumn(1).setMaxWidth(90);
        tablica.getColumn(1).setHeaderValue("Datum");
        tablica.getColumn(1).setDateFormat("dd/MM/yyyy");
        //Tipster id
        tablica.getColumn(2).setVisible(false);
        //Tipster naziv
        tablica.getColumn(3).setMinWidth(100);
        tablica.getColumn(3).setMaxWidth(100);
        tablica.getColumn(3).setHeaderValue("Tipster");
        //Opis
        //tablica.getColumn(4).setVisible(false);      
        tablica.getColumn(4).setMinWidth(150);
        tablica.getColumn(4).setMaxWidth(150);
        tablica.getColumn(4).setHeaderValue("Opis");
        //Ulog
        tablica.getColumn(5).setMinWidth(80);
        tablica.getColumn(5).setMaxWidth(80);
        tablica.getColumn(5).setHeaderValue("Ulog");
        //Koeficijent
        tablica.getColumn(6).setMinWidth(100);
        tablica.getColumn(6).setMaxWidth(100);
        tablica.getColumn(6).setHeaderValue("Koeficijent");
        //Dobitak
        tablica.getColumn(7).setMinWidth(90);
        tablica.getColumn(7).setMaxWidth(90);
        tablica.getColumn(7).setHeaderValue("Ev. dobitak");
        //Saldo
        tablica.getColumn(8).setMinWidth(90);
        tablica.getColumn(8).setMaxWidth(90);
        tablica.getColumn(8).setHeaderValue("Saldo");
        //Status id
        tablica.getColumn(9).setVisible(false);
        //Status naziv
        tablica.getColumn(10).setMinWidth(90);
        tablica.getColumn(10).setMaxWidth(90);
        tablica.getColumn(10).setHeaderValue("Status");
        // Igram
        Pomocna.instalirajCheckBox(tablica, 11);
        tablica.getColumn(11).setHeaderValue("Igram");
        tablica.getColumn(11).setMinWidth(80);
        tablica.getColumn(11).setMaxWidth(80);

        //Napomena            
        tablica.getColumn(12).setHeaderValue("Napomena");

        TablicaSkin skin = new TablicaSkin();
        tablica.setSkin(skin);
        Object put = UIManager.put("Table.gridColor", Color.black);

    }

    private void lokacijaPoljaTotala() {
        int x = 390;
        Point tocka = jFormattedTextFieldSUlog.getLocation();
        jFormattedTextFieldSUlog.setLocation(x, tocka.y);
        x = x + 80 + 100;
        jFormattedTextFieldSDobitak.setLocation(x, tocka.y);
        x = x + 90;
        jFormattedTextFieldSSaldo.setLocation(x, tocka.y);
        x = x + 90;
        jFormattedTextFieldSROI.setLocation(x, tocka.y);
    }

    private void napraviSelectSQL() {
        String sql = "SELECT\n"
                + "    A.Id,\n"
                + "    A.Datum,\n"
                + "    A.TIPSTER_ID Tipster,\n"
                + "    C.Naziv,\n"
                + "    A.Opis Opis,\n"
                + "    A.Ulog,\n"
                + "    A.Koeficijent,\n"
                + "    A.Dobitak,\n"
                + "    A.Saldo,\n"
                + "    A.STATUS_ID Status,\n"
                + "    B.Naziv,\n"
                + "    A.Igram,\n"
                + "    A.Napomena\n"
                + "FROM\n"
                + "    PROMET A\n"
                + "    JOIN STATUS B ON B.ID=A.STATUS_ID\n"
                + "    JOIN TIPSTER C ON C.ID=A.TIPSTER_ID ";
        String where = "";
        String orderBy = " ";
        //Where
        where = napraviWhereSQL();
        sql = sql + where;
        // Order by
        orderBy = " ORDER BY A.Datum, A.Tipster_ID";
        sql = sql + orderBy;
        tablica.setSelectSql(sql);
    }

    private void totalSQL() {
        try {
            String sql = "SELECT       \n"
                    + "    COALESCE(SUM(A.Ulog),0) ULOG, \n"
                    + "    COALESCE(SUM(A.Dobitak),0) DOBITAK,\n"
                    + "    COALESCE(SUM(A.Saldo),0) SALDO,\n"
                    + "     COALESCE(ROUND(SUM(SALDO)/SUM(ULOG),3),0) ROI\n"
                    + "   \n"
                    + "FROM\n"
                    + "    PROMET A\n"
                    + "    JOIN STATUS B ON B.ID=A.STATUS_ID\n"
                    + "    JOIN TIPSTER C ON C.ID=A.TIPSTER_ID ";
            String where = "";
            //Where
            where = napraviWhereSQL();
            sql = sql + where;
            Statement stmt = Konekcija.konekcija.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            rs.first();
            jFormattedTextFieldSUlog.setValue(rs.getBigDecimal("ULOG"));
            jFormattedTextFieldSDobitak.setValue(rs.getBigDecimal("DOBITAK"));
            jFormattedTextFieldSSaldo.setValue(rs.getBigDecimal("SALDO"));
            jFormattedTextFieldSROI.setValue(rs.getBigDecimal("ROI"));
            rs.close();
        } catch (SQLException ex) {
            Poruka.greska(rootPane, ex.getMessage());
        }


    }

    private String napraviWhereSQL() {
        String where = " where ";
        //Datum od do
        where = where + " A.DATUM BETWEEN " + Pomocna.TekstDatumUSQLDatum(jFormattedTextFieldDatumOd.getText()) + " AND "
                + Pomocna.TekstDatumUSQLDatum(jFormattedTextFieldDatumDo.getText());
        //Tipster
        if (!jTextFieldTipsterNaziv.getText().equals("")) {
            where = where + " AND A.TIPSTER_ID=" + jFormattedTextFieldTipster.getValue();
        }
        //Status       
        where = where + " AND A.STATUS_ID IN(1,2)";
        //Igram
        if (jComboBoxIgram.getSelectedIndex() != 2) {
            where = where + " AND A.IGRAM=" + jComboBoxIgram.getSelectedIndex();
        }
        return where;
    }
    private void jFormattedTextFieldTipsterPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jFormattedTextFieldTipsterPropertyChange
        if (evt.getPropertyName().equals("value")) {
            Tipster tipster = PomocnaBaza.getTipster(evt.getNewValue());
            jTextFieldTipsterNaziv.setText(tipster.getNaziv());
            //jCheckBoxIgram.setSelected(tipster.getIgram() != null && tipster.getIgram().equals("1"));
        }
    }//GEN-LAST:event_jFormattedTextFieldTipsterPropertyChange

    private void jButtonIzlazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzlazActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonIzlazActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIzlaz;
    private javax.swing.JComboBox jComboBoxIgram;
    private javax.swing.JFormattedTextField jFormattedTextFieldDatumDo;
    private javax.swing.JFormattedTextField jFormattedTextFieldDatumOd;
    private javax.swing.JFormattedTextField jFormattedTextFieldSDobitak;
    private javax.swing.JFormattedTextField jFormattedTextFieldSROI;
    private javax.swing.JFormattedTextField jFormattedTextFieldSSaldo;
    private javax.swing.JFormattedTextField jFormattedTextFieldSUlog;
    private javax.swing.JFormattedTextField jFormattedTextFieldTipster;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldTipsterNaziv;
    private quick.dbtable.DBTable tablica;
    // End of variables declaration//GEN-END:variables
}
